- job_name: 'blackbox'
    metrics_path: /probe
    params:
      module: [http_2xx]  # Look for a HTTP 200 response.
    static_configs:
      - targets:
          - http://prometheus.io    # Target to probe with HTTP.
          - http://<APP_SERVER-public-ip>:3000
          - https://prime-video.soumosarkar.xyz  # Target to probe with HTTPS.
    relabel_configs:
      - source_labels: [__address__]
        target_label: __param_target
      - source_labels: [__param_target]
        target_label: instance
      - target_label: __address__
        replacement: <Monitoring_Server-public-ip>:9115  # The blackbox exporter's real hostname.

- job_name: 'jenkins'
    metrics_path: '/prometheus'
    static_configs:
      - targets:
          - '<APP_SERVER-public-ip>:8080'


- job_name: node_exporter
  static_configs:
     - targets:
          - '<APP_SERVER-public-ip>:9100'
